immobiliare/backstage-plugin-gitlab

- README.md
> fix: link gitlab on readme

- README.md
- src/api/GitlabCIClient.ts
- src/api/index.ts
- src/components/types.ts
- src/index.ts
This PR exports the API ref and all types to allow API extensibility. 
> feat: added api extendibility

- src/components/utils.tsx
I formatted the durations with the following format: 
> fix: formatted durations

- package.json
- src/components/utils.tsx
- src/components/widgets/MergeRequestStats/MergeRequestStats.tsx
Migrated to dayjs.
close https://github.com/immobiliare/backstage-plugin-gitlab/issues/13
> chore: removed moment and added dayjs

- package-lock.json
- package.json
> chore: update package lock

- src/api/GitlabCIClient.ts
Fix default, now filePath default works
> fix: default filepath

- README.md
> docs: improved documentation and add Code Owners feature bullet

- src/api/GitlabCIClient.ts
- src/components/widgets/PeopleCard/PeopleCard.tsx
- src/components/widgets/PeopleCard/components/PeopleList/PeopleList.tsx
Handled Missing CODEOWNERS file in repository
Closes #26 
> feat(CODEOWNERS): handled missing file

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/api/GitlabCIClient.ts
- src/components/widgets/PeopleCard/PeopleCard.tsx
- src/components/widgets/PeopleCard/components/PeopleList/PeopleList.tsx
> Release v2.1.0

- src/components/widgets/IssuesTable/IssuesTable.tsx
- src/components/widgets/PeopleCard/PeopleCard.tsx
This is a fix, now code owners works with project slug
> fix: code owners and issues do not work with project slug

- dev/index.tsx
- src/components/widgets/PeopleCard/PeopleCard.tsx
fix Missing details if project_slug is undefined
> fix: people card fix

- README.md
- docs/migration-guides.md
- packages/gitlab-backend/README.md
- packages/gitlab-backend/src/processor/processor.test.ts
- packages/gitlab-backend/src/processor/processor.ts
- packages/gitlab/README.md
- packages/gitlab/config.d.ts
- packages/gitlab/src/api/GitlabCIClient.ts
- packages/gitlab/src/plugin.ts
> Docs version 3

- package.json
- packages/gitlab-backend/package.json
- packages/gitlab/package.json
> fix(yarn): fix yarn version

- packages/gitlab/src/api/GitlabCIClient.ts
> Fix removed type

- README.md
> Fix docs path

- README.md
- docs/migration-guides.md
> docs: general documentation fixes

- README.md
> Docs removed broken badge

- packages/gitlab/src/components/widgets/MergeRequestsTable/MergeRequestsTable.tsx
- packages/gitlab/src/components/widgets/PipelinesTable/PipelinesTable.tsx
Added an empty array in MergeRequest and Pipelines Table in case those are undefined.
closes #84 
> fix(table): added empty array to table data in mr and pipeline tables

- package.json
`start` script fix in root directory.
> chore: start scripts in root dir fix

- README.md
Added ref to how to contribute section.
> Chore how to contribute ref

- packages/gitlab-backend/package.json
Removed unused `node-fetch` dep
> Chore removed not used dep

- packages/gitlab-backend/src/processor/processor.test.ts
- packages/gitlab-backend/src/processor/processor.ts
> Fix target is not well formatted url

- packages/gitlab-backend/src/processor/processor.ts
> chore: switched checks for efficiency reasons

- packages/gitlab/dev/mock-gitlab/api-v4-v15.7.0.ts
- packages/gitlab/package.json
- packages/gitlab/src/api/GitlabCIApi.ts
- packages/gitlab/src/api/GitlabCIClient.ts
- packages/gitlab/src/components/GitlabCI/GitlabCI.tsx
- packages/gitlab/src/components/types.ts
- packages/gitlab/src/components/widgets/ReleasesCard/ReleasesCard.tsx
- packages/gitlab/src/components/widgets/ReleasesCard/index.ts
- packages/gitlab/src/components/widgets/index.ts
- packages/gitlab/src/index.ts
- packages/gitlab/src/plugin.ts
closes #128 
- add widget ReleasesCard
- add API method getReleasesSummary according to other api calls (summary type, extract data, etc)
- add explicit dependency to @types/semver (already in yarn.lock) to let the widget filter releases
> feat(releasescard): add releases widget and api

- packages/gitlab-backend/src/service/router.ts
> fix: catching the error from http-proxy-middleware

- packages/gitlab-backend/src/service/router.ts
- packages/gitlab/src/components/widgets/PeopleCard/PeopleCard.tsx
- packages/gitlab/src/components/widgets/PeopleCard/components/PeopleList/PeopleList.tsx
- packages/gitlab/src/components/widgets/ReleasesCard/ReleasesCard.tsx
Fix the Keys errors and format the code.
> Fix code key error

- packages/gitlab-backend/src/service/router.ts
> fix: removeHeader throws an error

- README.md
- docs/migration-guides.md
- packages/gitlab/app-config.yaml
- packages/gitlab/config.d.ts
- packages/gitlab/dev/index.tsx
- packages/gitlab/dev/mock-gitlab/api-v4-v15.7.0.ts
- packages/gitlab/src/api/GitlabCIApi.ts
- packages/gitlab/src/api/GitlabCIClient.ts
- packages/gitlab/src/components/GitlabCI/GitlabCI.tsx
- packages/gitlab/src/components/gitlabAppData.tsx
- packages/gitlab/src/components/widgets/ReadmeCard/ReadmeCard.tsx
- packages/gitlab/src/components/widgets/ReadmeCard/index.ts
- packages/gitlab/src/components/widgets/index.ts
- packages/gitlab/src/index.ts
- packages/gitlab/src/plugin.ts
Introducing a new feature to load the README files from the project repository.
> feat: load README from the project repository

- packages/gitlab-backend/src/processor/processor.ts
- packages/gitlab/dev/index.tsx
- packages/gitlab/src/api/GitlabCIApi.ts
- packages/gitlab/src/api/GitlabCIClient.ts
- packages/gitlab/src/components/types.ts
- packages/gitlab/src/components/widgets/IssuesTable/IssuesTable.tsx
- packages/gitlab/src/components/widgets/LanguagesCard/LanguagesCard.tsx
- packages/gitlab/src/components/widgets/MergeRequestStats/MergeRequestStats.tsx
- packages/gitlab/src/components/widgets/MergeRequestsTable/MergeRequestsTable.tsx
- packages/gitlab/src/components/widgets/PeopleCard/PeopleCard.tsx
- packages/gitlab/src/components/widgets/PipelinesTable/PipelinesTable.tsx
- packages/gitlab/src/components/widgets/ReadmeCard/ReadmeCard.tsx
- packages/gitlab/src/components/widgets/ReleasesCard/ReleasesCard.tsx
Codebase refactoring making the code more readable. We had a lot of any type; I removed them.
> Refactor type and code refactor

- packages/gitlab/dev/index.tsx
- packages/gitlab/package.json
- packages/gitlab/src/api/GitlabCIApi.ts
- packages/gitlab/src/api/GitlabCIClient.ts
- packages/gitlab/src/api/index.ts
- packages/gitlab/src/components/types.ts
- packages/gitlab/src/components/widgets/IssuesTable/IssuesTable.tsx
- packages/gitlab/src/components/widgets/IssuesTable/columns.tsx
- packages/gitlab/src/components/widgets/LanguagesCard/LanguagesCard.tsx
- packages/gitlab/src/components/widgets/MergeRequestStats/MergeRequestStats.tsx
- packages/gitlab/src/components/widgets/MergeRequestsTable/Icons.tsx
- packages/gitlab/src/components/widgets/MergeRequestsTable/MergeRequestsTable.tsx
- packages/gitlab/src/components/widgets/MergeRequestsTable/columns.tsx
- packages/gitlab/src/components/widgets/PeopleCard/PeopleCard.tsx
- packages/gitlab/src/components/widgets/PipelinesTable/PipelinesTable.tsx
- packages/gitlab/src/components/widgets/PipelinesTable/columns.tsx
- packages/gitlab/src/components/widgets/ReadmeCard/ReadmeCard.tsx
- packages/gitlab/src/components/widgets/ReleasesCard/ReleasesCard.tsx
- yarn.lock
Migrated all types to gitbeaker types
> Feat migreted all types to gitbeaker

- packages/gitlab/src/api/GitlabCIApi.ts
- packages/gitlab/src/api/GitlabCIClient.ts
- packages/gitlab/src/components/types.ts
- packages/gitlab/src/components/widgets/PeopleCard/PeopleCard.tsx
API  and people card refactoring 
> refactor: api and People card

- packages/gitlab-backend/src/service/router.test.ts
- packages/gitlab-backend/src/service/router.ts
- packages/gitlab/dev/index.tsx
- packages/gitlab/dev/mock-gitlab/api-v4-v15.7.0.ts
- packages/gitlab/package.json
- packages/gitlab/src/api/GitlabCIApi.ts
- packages/gitlab/src/api/GitlabCIClient.ts
- packages/gitlab/src/components/widgets/CoverageCard/CoverageCard.tsx
- packages/gitlab/src/components/widgets/CoverageCard/index.ts
- packages/gitlab/src/components/widgets/index.ts
- packages/gitlab/src/index.ts
- packages/gitlab/src/plugin.ts
- yarn.lock
This MR adds a coverage card that displays the coverage graph for the last 30 days
-   [X] New feature (non-breaking change which adds functionality)
> feat: Add Coverage card

- packages/gitlab/src/api/GitlabCIClient.ts
> fix: graphql query

- packages/gitlab-backend/package.json
- packages/gitlab-backend/src/service/router.test.ts
- packages/gitlab-backend/src/service/router.ts
- packages/gitlab/src/api/GitlabCIClient.ts
- packages/gitlab/src/components/GitlabCI/GitlabCI.tsx
- packages/gitlab/src/components/widgets/CoverageCard/CoverageCard.tsx
- yarn.lock
> fix: reconverted body into a stream

- packages/gitlab/src/api/GitlabCIClient.ts
Added support to forward slashes in path of CODEOWNERS file used in app-config.yml (defaultCodeOwnersPath) and/or catalog-info.yaml (gitlab.com/codeowners-path)
-   [ x ] New feature (non-breaking change which adds functionality)
-   [ x ] Bugfix (non-breaking change which fixes an issue)
> feat(scope): Support use of forward slash in filepath of CODEOWNERS file

- packages/gitlab-backend/package.json
- packages/gitlab/package.json
- yarn.lock
> feat: bump dependencies

- packages/gitlab-backend/src/processor/processor.test.ts
- packages/gitlab-backend/src/processor/processor.ts
- packages/gitlab-backend/src/processor/urls.ts
> fix: subpath does not evaluate the right url

- README.md
- packages/gitlab-backend/package.json
- packages/gitlab-backend/src/index.ts
- packages/gitlab-backend/src/plugin.test.ts
- packages/gitlab-backend/src/plugin.ts
- yarn.lock
In this pr, support for registering plugins into the new backstage backend system.
Reference: https://backstage.io/docs/backend-system/building-plugins-and-modules/index
-   [ ] …
> feat: support register to the new backend system

- packages/gitlab/package.json
- yarn.lock
> feat: bump frontend deps

- README.md
- packages/gitlab-backend/config.d.ts
- packages/gitlab-backend/package.json
- packages/gitlab-backend/src/service/router.test.ts
- packages/gitlab-backend/src/service/router.ts
- packages/gitlab/config.d.ts
- packages/gitlab/src/api/GitlabCIClient.ts
- packages/gitlab/src/plugin.ts
- yarn.lock
> Feat: added oauth

- packages/gitlab-backend/src/service/router.ts
> refactor: unified headers maniputation operations

- README.md
Updating the initial contributors with their GitHub Profile on README.md
-   [ x] Documentation Update (if none of the other choices apply)
> feat: updating the initial contributors

- package.json
- packages/gitlab-backend/package.json
- packages/gitlab-backend/src/plugin.test.ts
- packages/gitlab/config.d.ts
- packages/gitlab/package.json
- packages/gitlab/src/api/GitlabCIClient.test.ts
- packages/gitlab/src/api/GitlabCIClient.ts
- packages/gitlab/src/plugin.ts
- yarn.lock
> feat: backstage deps and caching

- packages/gitlab/config.d.ts
- packages/gitlab/src/api/GitlabCIClient.test.ts
- packages/gitlab/src/api/GitlabCIClient.ts
- packages/gitlab/src/plugin.ts
> fix: disable cache by default

- packages/gitlab/src/api/GitlabCIApi.ts
- packages/gitlab/src/api/GitlabCIClient.test.ts
- packages/gitlab/src/api/GitlabCIClient.ts
I want to use this plugin to create a custom page in Backstage with summarised information from multiple plugins. One of the key information for us are the latest tags.
> feat(api): added api request for all tags from repository

- packages/gitlab/src/components/widgets/PeopleCard/PeopleCard.tsx
> feat: added possibility to disable members list

- README.md
> docs: added alpha to import
